#!/usr/bin/env bash
# Generate .env.prod with strong secrets. Interactive, idempotent if .env.prod
# does not already exist. Refuses to overwrite to prevent accidental rotation.
#
# Usage:
#   bash scripts/generate-env.sh

source "$(dirname "$0")/lib.sh"

require_cmd openssl
require_cmd curl

if [[ -f "$ENV_FILE" ]]; then
  warn ".env.prod already exists at $ENV_FILE — refusing to overwrite."
  warn "Edit it by hand, or delete it first if you want a clean regeneration."
  exit 1
fi

log "Generating $ENV_FILE"

read -rp "Domain (e.g. letsgo.example.com): " DOMAIN
[[ -n "$DOMAIN" ]] || die "Domain is required."

read -rp "Let's Encrypt email (for cert expiry notifications): " ACME_EMAIL
[[ -n "$ACME_EMAIL" ]] || die "Email is required."

DEFAULT_IP="$(curl -4 -s --max-time 5 ifconfig.me 2>/dev/null || true)"
read -rp "VM public IPv4 [${DEFAULT_IP}]: " TURN_EXTERNAL_IP
TURN_EXTERNAL_IP="${TURN_EXTERNAL_IP:-$DEFAULT_IP}"
[[ -n "$TURN_EXTERNAL_IP" ]] || die "Public IPv4 is required."

POSTGRES_PASSWORD="$(openssl rand -hex 24)"
LETSGO_JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
TURN_PASS="$(openssl rand -hex 16)"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
LETSGO_JWT_SECRET=${LETSGO_JWT_SECRET}

TURN_USER=letsgo
TURN_PASS=${TURN_PASS}
TURN_EXTERNAL_IP=${TURN_EXTERNAL_IP}
EOF
chmod 600 "$ENV_FILE"

ok "Wrote $ENV_FILE"
log "Generated secrets — store a backup somewhere safe:"
printf '  POSTGRES_PASSWORD=%s\n' "$POSTGRES_PASSWORD" >&2
printf '  LETSGO_JWT_SECRET=%s\n' "$LETSGO_JWT_SECRET" >&2
printf '  TURN_PASS=%s\n' "$TURN_PASS" >&2
